version: '{build}'

branches:
  only:
  - master
  - develop
  - release

clone_depth: 50

init:
  - cmd: git config --global core.autocrlf true
  - cmd: mvn --version

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  - JAVA_HOME: C:\Program Files\Java\jdk10

cache:
  - C:\Users\appveyor\.m2\

build_script:
  - cmd: mvn install -B

test: off

deploy: off
